- name: 'Coca Cola'
  quantity: 10
  price: 2.00
- name: 'Sprite'
  quantity: 10
  price: 2.50
- name: 'Fanta'
  quantity: 10
  price: 2.25
- name: 'Orange Juice'
  quantity: 10
  price: 3.00
- name: 'Water'
  quantity: 0
  price: 3.25
